---



- name: Add k8s repo signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes


- name: add k8s apt repository
  apt_repository: 
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main' 
    state: present  
  become: yes



- name: remove old version
  apt:
    pkg: "{{ item }}"
    state: absent
    update_cache: yes
  become: yes
  with_items:
    - kubeadm 
    - kubelet 
    - kubectl

- name: install k8s pkg
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubeadm 
    - kubelet 
    - kubectl
  become: yes

- name: make swap off 
  command: "swapoff --all"
  become: yes

- name: reset cluster
  become: yes
  shell: "kubeadm reset --force" 
    
- name: setup cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.10.0.0/16 
  when: inventory_hostname in groups['master']
  
- name: add config dir for user
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  when: inventory_hostname in groups['master']
  become: yes

- name: copy admin.conf file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /$HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_user | default(ansible_user_id) }}"
  when: inventory_hostname in groups['master']
  become: yes

- name: config wave network 
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: inventory_hostname in groups['master']
  become: yes

- name: get join command 
  when: inventory_hostname in groups['master']
  shell: kubeadm token create --print-join-command
  register: JoinCommand
  become: yes
  run_once: true

- name: get join command from master hostvar
  set_fact:
    jc: "{{ JoinCommand.stdout }}"
  when: inventory_hostname in groups['master']
  run_once: true

- name: join to cluster 
  shell:  "{{ jc }}"
  when: inventory_hostname in groups['worker']
  become: yes