---
- name: remove old version
  apt:
    pkg: "{{ items }}"
    state: absent
  sudo: yes
  with_items:
    - docker
    - docker-engine
    - docker.io 
    - containerd
    - runc

- name: Add docker repo signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository: 
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable' 
    state: present  
    update_cache: yes

- name: install docker pkg
  apt:
    pkg: "{{ items }}"
    state: present
    with_items:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
- name: enable docker service 
  systemd:
    name: docker
    state: started
    enabled: yes